### ISSUE TITLE
Pushing to Heroku(still learning)

### ISSUE THREAD

**Issue by Ankiewicz** [bradtraversy/loginapp#1]
I am still learning, so this is most likely just a realm of me not knowing what I am doing. But I am trying to push this application to heroku. So I can play with it in a production realm.

Any chance you can help me out and maybe point me in the right direction.

![screen shot 2016-07-16 at 12 56 17 pm](https://cloud.githubusercontent.com/assets/11892928/16896855/cdbf3222-4b54-11e6-8bbe-1c60d93ad32b.png)

**Comment by pjstol** [comment]
Were you able to make it work? I'm trying the same

**Comment by makemek** [comment]
It can't establish a connection to a non-existent database.
Heroku doesn't come with MongoDB pre-installed.
You need an online database storage.
I recommend using [mLab](https://mlab.com/home).
Register an account and create a database there.
Then, the connection in [app.js](https://github.com/bradtraversy/loginapp/blob/84c20c9b920dffc52b5a79f3e7c383f166eda92d/app.js#L14) to your database.
