### ISSUE TITLE
view engine

### ISSUE THREAD

**Issue by xubingyang** [bradtraversy/loginapp#10]
I am trying to change the view engine to EJS.
But I have some trouble with this part.
` <div class="row">
                <div class="col-lg-12">
                    {{#if success_msg}}
                        <div class="alert alert-success">{{success_msg}}</div>
                    {{/if}}
                    {{#if error_msg}}
                        <div class="alert alert-danger">{{error_msg}}</div>
                    {{/if}}
                    {{#if error}}
                        <div class="alert alert-danger">{{error}}</div>
                    {{/if}}
                    {{{body}}}
                </div>
            </div>`

any help?

**Comment by gabru-md** [comment]
@xubingyang 
You are trying to use a completely different View Engine.
You can try changing the syntax according to EJS View.

Try using the code below:

`<div class="rows">  <div class="col-lg-12">  <%= if(success_msg.length > 0){ %>    <%= success_msg.forEach(function(msg){%>      <div class="alert alert-success"><%= msg %></div>    <%= }) %>  <%= } %>  <%= if(error_msg.length > 0){ %>    <%= error_msg.forEach(function(err_msg){%>      <div class="alert alert-success"><%= err_msg %></div>    <%= }) %>  <%= } %>  </div></div>`
In any case of problem please contact.

PS: I am a beginner as well.

**Comment by pipegreyback** [comment]
Hey ! I am also trying to use this with EJS, my code for that section is the following:
```
<% if(locals.success_msg){ %>
	<div class="alert alert-success">
		<%= success_msg %>
	</div>
	<% } %>
<% if(locals.error_msg){ %>
	<div class="alert alert-success">
		<%= err_msg %>
	</div>
	<% } %>
```
The issue I am having is that if I don't use the `locals`, before the var who has the data, or the one which would output (success_msg, or err_msg) it throws me the error: `success_msg is not defined`.
