### ISSUE TITLE
duplicate record

### ISSUE THREAD

**Issue by sghpyankae1986** [bradtraversy/loginapp#13]
Hello, I am very new for this and really appreciate if you guys help me to fix.
Registration page, currently i can submit duplicate record. how to fix if user is already exist in db based on user's email. Thanks

**Comment by Saspect-IO** [comment]
Modify your model to the code below:
This will stop duplicate Values

var UserSchema = mongoose.Schema({
	username: {
		type: String,
		unique:true,
		index:true,
		dropDups: true
	},
	password: {
		type: String
	},
	email: {
		type: String,
		unique: true,
		dropDups: true
	},
	name: {
		type: String
	}
}, { collection : 'Users' });

var User = module.exports = mongoose.model('User', UserSchema);

**Comment by Saspect-IO** [comment]
Also to check if user already exist please see link https://stackoverflow.com/questions/35008433/i-am-using-node-js-promise-for-validating-either-username-exist-in-db-or-not.
