### ISSUE TITLE
Include statement in ejs file not correct

### ISSUE THREAD

**Issue by kevintagline** [bradtraversy/loginapp#131]
In login.ejs and register.ejs files include statements are not correct, which is causing following error 
`SyntaxError: Unexpected token '/' in /Users/tagline/node_passport_login/views/login.ejs while compiling ejs`

**Comment by AElgamal5** [comment]
Try this line:
```
<%- include('./partials/messages.ejs') %>
```
instead of
```
<% include ./partials/messages %>
```
