### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by sushantshekhar20** [bradtraversy/loginapp#17]
(node:2137) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client

**Comment by fhdalv** [comment]
The latest version has this issue though the server works fine. I used 4.10.8 to get rid of this.

**Comment by sushantshekhar20** [comment]
Thanks @fhdalv  😺
