### ISSUE TITLE
Why is Mongo throwing this error?

### ISSUE THREAD

**Issue by DJN1** [bradtraversy/loginapp#22]
`(node:10576) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to conn
ect to server [localhost:27017] on first connect [MongoNetworkError: connect ECO
NNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Users\xxxxxx\Documents\GitHub\website_test
\loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.
js:505:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (C:\Users\xxxxxxx\Documents\GitHub\website_test\loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:329:1
2)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (C:\Users\xxxxxxxx\Documents\GitHub\website_test\loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:245
:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:10576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or b
y rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js pr
ocess with a non-zero exit code.`
What is the solution to this. I tried a couple of things but I can't figure it out.
Thanks

**Comment by tomcatbuzz** [comment]
Read the error, the first line explains the problem ```MongoNetworkError: failed to conn ect to server [localhost:27017] on first connect``` your MongoD was not started and didn't connect. Make sure the service is started on your pc. 
    On Friday, April 20, 2018, 11:23:15 AM EDT, DJN1 <notifications@github.com> wrote:  
 
 
(node:10576) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to conn ect to server [localhost:27017] on first connect [MongoNetworkError: connect ECO NNREFUSED 127.0.0.1:27017] at Pool.<anonymous> (C:\Users\xxxxxx\Documents\GitHub\website_test \loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server. js:505:11) at emitOne (events.js:116:13) at Pool.emit (events.js:211:7) at Connection.<anonymous> (C:\Users\xxxxxxx\Documents\GitHub\website_test\loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:329:1 2) at Object.onceWrapper (events.js:317:30) at emitTwo (events.js:126:13) at Connection.emit (events.js:214:7) at Socket.<anonymous> (C:\Users\xxxxxxxx\Documents\GitHub\website_test\loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:245 :50) at Object.onceWrapper (events.js:315:30) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at emitErrorNT (internal/streams/destroy.js:64:8) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9) (node:10576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or b y rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:10576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js pr ocess with a non-zero exit code.

**Comment by DJN1** [comment]
How do I start the process? I tried navigating to `C:/Program Files/MongoDB/Server/3.6/bin` and tried executing `mongod` but cmd doesnt recognize the command.
Thanks

**Comment by tomcatbuzz** [comment]
Go to Computer Management Console under Services and look for Mongo, then select start, you can also set it to automatic. You will still need to open the C:/Program Files/MongoDB/Server/3.6/bin in your command line and run mongo start. You should research some videos on youtube and the Mongo Website to make sure you have the correct set up. This will let Mongo Service start with Windows and you will just need to run mongo start in cli. 
    On Sunday, April 22, 2018, 5:58:56 PM EDT, DJN1 <notifications@github.com> wrote:  
 
 
How do I start the process? I tried navigating to C:/Program Files/MongoDB/Server/3.6/bin and tried executing mongod but cmd doesnt recognize the command.
Thanks

**Comment by DJN1** [comment]
Yeah I figured it out. I basically added mongo to the `PATH` and now I can just start it. Thanks alot!
