### ISSUE TITLE
can't login 

### ISSUE THREAD

**Issue by marselgray** [bradtraversy/loginapp#26]
Hey Brad, great videos. I'm attempting to learn node.js and passport. When I go to login I get a 404 error. I even attempted to download your copy and try it from there and get the same result. I followed your YouTube presentation on it but I can't seem to locate the bug. Any ideas?

**Comment by marselgray** [comment]
nevermind bro, I'm just new to this.

**Comment by devils-ey3** [comment]
@marselgray Do you check you get register on your database ???

**Comment by aadhil96** [comment]
![screenshot 64](https://user-images.githubusercontent.com/28821226/45594182-3fde0200-b94b-11e8-8c39-e89bec377b48.png)


how to solve this in handlebars
