### ISSUE TITLE
node app?

### ISSUE THREAD

**Issue by perogi** [bradtraversy/loginapp#4]
Hi Brad,

Your README file states to use npm start. I am getting the following error
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Did you mean to write `node app`?

Thanks!
perogi.

**Comment by xupertheo** [comment]
The commit will fix the bug with npm start, so npm start does work

**Comment by perogi** [comment]
Thanks!

**Comment by 2pay** [comment]
first, you must run `$npm install` when config mongodb connect. Run app by `npm start`

**Comment by xupertheo** [comment]
I think this issue should be closed...
