### ISSUE TITLE
(node:7924) DeprecationWarning

### ISSUE THREAD

**Issue by Alexandru-Stancu** [bradtraversy/loginapp#9]
I'm getting this error when I try to submit a registration form under a new user.
![image](https://cloud.githubusercontent.com/assets/26849102/25056755/a6282250-2173-11e7-8ba3-83c5b5a45d95.png)

**Comment by Ash-Bash** [comment]
I'm getting the same error at the same place, I cant explain why :(

**Comment by gabru-md** [comment]
ReferenceError occurs when we forget to capture the data under a variable name.
Check if variable 'err' exists.
And try replacing it with a string or something to check if the problem persists.
